export const SHARED_BUCKET_COUNT = 60;

export const HEARTBEAT_BUCKET_SECONDS = SHARED_BUCKET_COUNT;
export const HEARTBEAT_BUCKET_COUNT = SHARED_BUCKET_COUNT;
export const MODEL_LOG_RETENTION_COUNT = SHARED_BUCKET_COUNT;
export const MODEL_BUCKET_RETENTION_COUNT = SHARED_BUCKET_COUNT;
